POST http://localhost:3000/api/v1/todo-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoa2xhenRAZ21haWwuY29tIiwiaWQiOiIzMTNmYzAzNy0yYmY5LTQxZWMtODkyMS0zODI5NjU2ZmZkMDciLCJpYXQiOjE3Mjc4MDI3OTIsImV4cCI6MTcyNzgwNDU5Mn0.Dc14eEVldXWgmFH7-v_eaiNZC_bSFyvxtuJF8eHDgw8

{
  "title": "My todo list"
}